{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./dressing.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lualine.nix
    ./mini-indentscope.nix
    ./noice.nix
    ./notify.nix
    ./nui.nix
    ./oil.nix
    ./telescope.nix
    ./whichkey.nix
  ];
}
