{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./diffview.nix
    ./dressing.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./illuminate.nix
    ./image.nix
    ./indent-blankline.nix
    ./lualine.nix
    ./neogit.nix
    ./noice.nix
    ./notify.nix
    ./nui.nix
    ./oil.nix
    ./overseer.nix
    ./stickybuf.nix
    ./telescope.nix
    ./todo-comments.nix
    ./toggleterm.nix
    ./trouble.nix
    ./whichkey.nix
  ];
}
