{
  imports = [
    ./autopairs.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./dap.nix
    ./flash.nix
    ./lint.nix
    ./lsp.nix
    ./mini.nix
    ./snippets.nix
    ./test.nix
    ./tmux-navigator.nix
    ./treesitter-context.nix
    ./treesitter-textobjects.nix
    ./treesitter.nix
    ./ufo.nix
    ./yanky.nix
  ];
}
