{
  imports = [
    ./auto-session.nix
    ./autopairs.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./dap.nix
    ./flash.nix
    ./icons.nix
    ./inc-rename.nix
    ./lint.nix
    ./lsp.nix
    ./mini.nix
    ./neogen.nix
    ./neorg.nix
    ./otter.nix
    ./refactoring.nix
    ./snippets.nix
    ./spectre.nix
    ./test.nix
    ./tmux-navigator.nix
    ./treesitter-context.nix
    ./treesitter-textobjects.nix
    ./treesitter.nix
    ./ufo.nix
    ./yanky.nix
  ];
}
